# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stickman
email: 97alfredosv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stickman es un juego de plataformas escrito en Java, el objetivo es simple
  obtener la llave, ya mencione que corre en la consola?.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  alfr3dosv

# Build settings
markdown: kramdown
